steps:
  - label: ":docker: Build/Test/Tag"
    command:
      - docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $${PIPELINE_DOCKER_REGISTRY_URL}:$${PIPELINE_IMAGE_TAG} .
      - docker run --rm $${PIPELINE_DOCKER_REGISTRY_URL}:$${PIPELINE_IMAGE_TAG} $$PIPELINE_TEST_DOCKER_IMAGE_COMMAND
      - docker login  -u $$DOCKER_USER -p $$DOCKER_PASS
    env:
        PIPELINE_DOCKER_IMAGE: ${PIPELINE_DOCKER_IMAGE}
        PIPELINE_TEST_DOCKER_IMAGE_COMMAND: ${PIPELINE_TEST_DOCKER_IMAGE_COMMAND}
        PIPELINE_DOCKER_REGISTRY_URL: ${PIPELINE_DOCKER_REGISTRY_URL}
        PIPELINE_IMAGE_TAG: ${PIPELINE_IMAGE_TAG}
        DOCKER_USER: $DOCKER_USER
        DOCKER_PASS: $DOCKER_PASS
    agents:
      queue: 'default'

  - wait

  - label: ":docker: Push"
    command: |
      set -eu
        docker push $${PIPELINE_DOCKER_REGISTRY_URL}:$${PIPELINE_IMAGE_TAG}
        cat << EOF | buildkite-agent annotate --style 'success'
        Docker image built: <b>$$PIPELINE_IMAGE_TAG</b>

      EOF
    env:
        PIPELINE_DOCKER_IMAGE: ${PIPELINE_DOCKER_IMAGE}
        PIPELINE_DOCKER_REGISTRY_URL: ${PIPELINE_DOCKER_REGISTRY_URL}
        PIPELINE_IMAGE_TAG: ${PIPELINE_IMAGE_TAG}
    agents:
      queue: 'default'
