steps:
  - label: ":docker: Build/Test/Tag"
    command:
      - ./buildkite/build_and_tag_docker.sh
    env:
        PIPELINE_TEST_DOCKER_IMAGE_COMMAND: ${PIPELINE_TEST_DOCKER_IMAGE_COMMAND}
        PIPELINE_DOCKER_REGISTRY_URL: ${PIPELINE_DOCKER_REGISTRY_URL}
        PIPELINE_IMAGE_TAG: ${PIPELINE_IMAGE_TAG}
    agents:
      queue: 'default'

  - wait

  - label: ":docker: Push"
    command: |
      set -eu
        docker push $${PIPELINE_DOCKER_REGISTRY_URL}:$${PIPELINE_IMAGE_TAG}
        cat << EOF | buildkite-agent annotate --style 'success'
        Docker image built: <b>$$PIPELINE_IMAGE_TAG</b>

      EOF
    env:
        PIPELINE_DOCKER_REGISTRY_URL: ${PIPELINE_DOCKER_REGISTRY_URL}
        PIPELINE_IMAGE_TAG: ${PIPELINE_IMAGE_TAG}
    agents:
      queue: 'default'
